# custom app config
# overrides DCAPE/apps/drone/dcape-app/docker-compose.yml

version: '2'

services:
  app:
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./config:/etc/dendrite
      - ${DCAPE_ROOT}/${DATA_PATH}/config:/etc/dendrite
      - ${DCAPE_ROOT}/${DATA_PATH}/media:/var/dendrite/media
    command:
      --tls-cert=server.crt --tls-key=server.key
    labels:
      - "traefik.http.services.app-${APP_TAG}.loadbalancer.server.port=8008"
