# custom app config
# overrides DCAPE/apps/drone/dcape-app/docker-compose.yml

services:
  app:
    image: ${IMAGE}:${IMAGE_VER}
    labels:
      - traefik.enable=true
      - dcape.traefik.tag=${DCAPE_TAG}
      - traefik.http.routers.${APP_TAG}.rule=Host(`${APP_SITE}`) && (PathPrefix(`/_matrix/`) || PathPrefix(`/_synapse/client`))
      - traefik.http.routers.${APP_TAG}.tls=${USE_TLS}
      - traefik.http.routers.${APP_TAG}.tls.certresolver=default
      - traefik.http.services.${APP_TAG}.loadbalancer.server.port=8008
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/ssl/certs:/etc/ssl/certs:ro
      - ${APP_ROOT}/config:/etc/dendrite
      - ${APP_ROOT}/data:/var/dendrite
    restart: always
    command:
      --tls-cert=server.crt --tls-key=server.key

  syncv3:
    image: $SYNCV3_IMAGE
    labels:
      - traefik.enable=true
      - dcape.traefik.tag=${DCAPE_TAG}
      - traefik.http.routers.${APP_TAG}-sync.rule=Host(`${APP_SITE}`)
      - traefik.http.services.${APP_TAG}-sync.loadbalancer.server.port=8008
      - traefik.http.routers.${APP_TAG}-sync.tls=${USE_TLS}
      - traefik.http.routers.${APP_TAG}-sync.tls.certresolver=default
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/ssl/certs:/etc/ssl/certs:ro
    restart: always
    depends_on:
      - app
    environment:
      - SYNCV3_SERVER=http://app:8008
      - SYNCV3_DB=postgres://${PGUSER}:${PGPASSWORD}@db/${SYNCV3_DB}?sslmode=disable
      - SYNCV3_SECRET

networks:
  default:
    name: ${DCAPE_NET}
    external: true
